const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const ENCREASE_PRODUCT = "ENCREASE_PRODUCT";
const DECREASE_PRODUCT = "DECREASE_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";

export {
    ADD_PRODUCT_TO_CART,
    ENCREASE_PRODUCT,
    DECREASE_PRODUCT,
    DELETE_PRODUCT
}